# Generated by Django 3.2.9 on 2022-04-06 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('m', 'Man'), ('w', 'Woman')], default='m', max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='public_stat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='stats.publicstatisticsmodel'),
        ),
    ]
