# Generated by Django 3.2.9 on 2022-04-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advt', '0002_auto_20220409_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='delete_date',
            new_name='del_date',
        ),
        migrations.RenameField(
            model_name='postmodel',
            old_name='date_pub',
            new_name='pub_date',
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='city',
            field=models.CharField(max_length=2),
        ),
    ]
